name: "I will creating action with merge all file in action"

on: 
  push: 
    branches: 
      - main
      - branch2

jobs:
  merge_all_file:
    runs-on: ubuntu-latest

    steps:
      - name: "Print Fruits"

        run: |
          echo "Apple"
          echo "Pappy"
          echo "Strawberry"
          echo "Pineapply"
          echo "Blackberry"

      - name: "Print price"

        run: |
          echo 10
          echo 20
          echo 40
          echo 30
          echo 10
          

          
          
      
